In [1]:
from collections import defaultdict

import numpy as np
import pandas as pd

from pcntoolkit.dataio.norm_data import NormData
from pcntoolkit.normative_model import NormativeModel

In [2]:
n_subjects = 100
n_samples = 150

subjects = np.random.choice(n_subjects, n_samples, replace=True)
coefs = np.random.rand(n_subjects, 2)
covariates = np.random.choice(10, n_samples, replace=True) + 1
responses1 = covariates + 0.1 * covariates * coefs[subjects, 0] + np.random.randn(n_samples) * 0.03
responses2 = covariates + 0.1 * covariates * coefs[subjects, 1] + np.random.randn(n_samples) * 0.03

df = pd.DataFrame(
    {"subjects": subjects, "age": covariates, "resp1": responses1, "resp2": responses2},
)
data = NormData.from_dataframe(
    name="dummy", dataframe=df, covariates=["age"], response_vars=["resp1", "resp2"], subject_ids="subjects"
)
df

Warning: remove_NAN is set to False. Missing (NaN) values may cause errors during model creation or training.
Process: 80433 - 2025-05-02 12:32:54 - Dataset "dummy" created.
    - 150 observations
    - 83 unique subjects
    - 1 covariates
    - 2 response variables
    - 1 batch effects:
    	dummy_batch_effect (1)

     subjects  age     resp1     resp2
0          35    9  9.699967  9.801820
1          34    9  9.118344  9.646651
2          60    1  1.093743  1.095564
3          70    4  4.164671  4.191412
4          93    5  5.006296  5.236032
..        ...  ...       ...       ...
145        74    6  6.066574  6.146404
146        76    5  5.063617  5.282624
147        79    4  4.067522  4.194909
148        35    6  6.483141  6.552219
149        31    7  7.412454  7.468652

[150 rows x 4 columns]

In [3]:
data.to_dataframe()

      X         Y                batch_effects subjects
    age     resp1     resp2 dummy_batch_effect subjects
0     9  9.699967  9.801820                0.0       35
1     9  9.118344  9.646651                0.0       34
2     1  1.093743  1.095564                0.0       60
3     4  4.164671  4.191412                0.0       70
4     5  5.006296  5.236032                0.0       93
..   ..       ...       ...                ...      ...
145   6  6.066574  6.146404                0.0       74
146   5  5.063617  5.282624                0.0       76
147   4  4.067522  4.194909                0.0       79
148   6  6.483141  6.552219                0.0       35
149   7  7.412454  7.468652                0.0       31

[150 rows x 5 columns]

In [56]:
def thrivelines(model: NormativeModel, data: NormData, bandwidth=5, covariate_name="age"):
    print(data.subjects)
    df = data.to_dataframe().droplevel(0, axis=1)
    groups = defaultdict(lambda: []) | df.groupby("age").groups
    print(df)
    # for age_1, age_2 in offset_indices(df["age"].max(), bandwidth):
    #     joint = pd.merge(df.iloc[groups[age_1]], df.iloc[groups[age_2]], how="inner", on="subject")


# """
# def sparse_correlation_matrices(subjects, age, responses, dc_max):
#     Create groups{age:df} dict
#     For ages i,j:
#         joint = inner merge groups[i] and groups[j] on subject
#         for column of responses:
#             correlation_matrix[responses,i,j] = corr(joint[responses_x], joint[responses_y])

# """
thrivelines(None, data)

<xarray.DataArray 'subjects' (subjects: 150)> Size: 1kB
array([15,  4,  6, 87, 21, 75, 58, 25, 85, 36, 66, 15, 16, 62, 12, 72, 92,  0,
        9, 89, 29, 35, 42, 39, 31, 28, 96, 63, 13, 59, 51, 76, 68, 75, 24, 62,
        5, 50, 17, 69, 11, 88, 15, 95,  7, 21, 76, 72, 55, 64, 94, 63, 51, 17,
        5, 78, 23, 11, 24, 33, 72, 17, 92, 82, 35, 96, 34, 23, 23, 75, 52, 50,
       16, 96, 28, 79, 34, 77, 35,  4, 18, 88, 77, 24, 66, 43,  5, 16,  7, 58,
       50, 40, 55, 15, 57, 75, 58, 19, 24, 27, 26, 61, 55, 25, 75, 82, 56, 28,
       35,  8, 76, 58, 93, 15, 48, 68, 29, 39,  5, 65,  4, 92, 77,  5, 25, 78,
       89, 59, 27, 90, 46, 72, 85, 82, 87, 88, 93, 65, 19, 14, 71, 16, 93,  3,
       75, 83, 97, 70, 24, 31])
Coordinates:
  * subjects  (subjects) int64 1kB 15 4 6 87 21 75 58 25 ... 3 75 83 97 70 24 31

ValueError: Index contains duplicate entries, cannot reshape